package denguestatisticssystem;

import java.time.Year;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Stream;
import javax.swing.table.DefaultTableModel;

public class MainPanel extends javax.swing.JPanel {
    public MainPanel(List<DengueCase> dengueCasesList, BidirectionalMap<Integer, Year> yearMap, BidirectionalMap<Integer, String> districtMap) {
        initComponents();

        // display dengue cases in table
        displayDengueCases(dengueCasesList, yearMap, districtMap);
    }

    // bind dengue cases list to table
    private void displayDengueCases(List<DengueCase> dengueCasesList, BidirectionalMap<Integer, Year> yearMap, BidirectionalMap<Integer, String> districtMap) {
        // create default table model
        DefaultTableModel model = (DefaultTableModel) tblDengueCases.getModel();

        // get multi-dimensional arraylist
        List<List<Object>> dengueCasesObjectList = convertDengueCasesToMultiDimensionalArrayList(dengueCasesList, yearMap, districtMap);

        // copy data to table model
        dengueCasesObjectList.forEach(district -> {
            model.addRow(district.toArray());
        });

        // add total dengue cases to table
        model.addRow(
            Stream.concat(
                // add state name
                Arrays.stream(new Object[] {"Pahang"}),
                // copy calculated total dengue cases per year
                Arrays.stream(totalDengueCasesPerYear(dengueCasesList, yearMap).toArray())
            )
            .toArray()
        );
    }

    // convert list of dengue case to multi-dimensional arraylist
    private static List<List<Object>> convertDengueCasesToMultiDimensionalArrayList(List<DengueCase> dengueCasesList, BidirectionalMap<Integer, Year> yearMap, BidirectionalMap<Integer, String> districtMap) {
        // initialise multi-dimensional arraylist
        List<List<Object>> convertedList = new ArrayList<>();
        districtMap.entrySet()
            .forEach(district -> {
                convertedList.add(new ArrayList<>());
                List<Object> yearList = convertedList.get(district.getKey());
                // initialise nested arraylist
                yearMap.entrySet()
                    .forEach(year -> yearList.add(0));
                yearList.add(0);
            });

        // copy data to multi-dimensional arraylist
        dengueCasesList.forEach(dengueCase -> {
            List<Object> district = convertedList.get(districtMap.getKey(dengueCase.getDistrict()));
            // add district name
            district.set(0, dengueCase.getDistrict());
            // copy district cases for each year
            district.set(yearMap.getKey(dengueCase.getYear()) + 1, dengueCase.getCases());
        });

        return convertedList;
    }

    // get total number of dengue cases per year
    private static List<Integer> totalDengueCasesPerYear(List<DengueCase> dengueCasesList, BidirectionalMap<Integer, Year> yearMap) {
        // initialise array list of integers
        List<Integer> cases = new ArrayList<>();
        yearMap.entrySet()
            .forEach(year -> cases.add(0));

        // loop through dengue cases list
        dengueCasesList.forEach(dengueCase ->
            // set the cumulative cases
            cases.set(
                // use index from year bidirectional map
                yearMap.getKey(dengueCase.getYear()),
                // get total number of cases and add current cases
                cases.get(yearMap.getKey(dengueCase.getYear())) + dengueCase.getCases()
            )
        );

        // return list of cases according to year bidirectional map
        return cases;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDengueCases = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(452, 427));
        setPreferredSize(new java.awt.Dimension(452, 427));

        jScrollPane1.setMinimumSize(new java.awt.Dimension(452, 427));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(452, 427));

        tblDengueCases.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "District", "2014", "2015", "2016", "2017", "2018", "2019"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDengueCases);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDengueCases;
    // End of variables declaration//GEN-END:variables
}
